### ISSUE TITLE
does not compile on 4.4.26

### ISSUE THREAD

**Issue by kpande** [tsutsu/btier#4]
```
make -Wall -C /lib/modules/4.4.26/build M=/root/btier/kernel/btier modules
make[1]: Entering directory `/usr/src/kernels/4.4.26'
  CC [M]  /root/btier/kernel/btier/btier_common.o
  CC [M]  /root/btier/kernel/btier/btier_sysfs.o
  CC [M]  /root/btier/kernel/btier/btier_main.o
/root/btier/kernel/btier/btier_main.c: In function ‘order_devices’:
/root/btier/kernel/btier/btier_main.c:1486: error: too many arguments to function ‘lookup_bdev’
/root/btier/kernel/btier/btier_main.c: In function ‘tier_set_fd’:
/root/btier/kernel/btier/btier_main.c:1802: error: too many arguments to function ‘lookup_bdev’
make[2]: *** [/root/btier/kernel/btier/btier_main.o] Error 1
make[1]: *** [_module_/root/btier/kernel/btier] Error 2
make[1]: Leaving directory `/usr/src/kernels/4.4.26'
make: *** [default] Error 2
```

**Comment by celesteking** [comment]
solved via https://github.com/celesteking/btier/commits/kernel-4.4 
or as I see you did the same.
